export const palavrasPortugues = [
 // --- básicas originais ---
    "arrombado", "arrombada", "babaca", "bosta", "boiola",
    "cacete", "caralho", "corno", "cu", "cuzão", "cuzao",
    "desgraçado", "desgracado", "fdp", "filho da puta",
    "filhodaputa", "foda", "foder", "fodase", "foda-se",
    "merda", "otário", "otario", "piranha", "porra", "puta",
    "puto", "vadia", "viado", "veado", "vagabundo", "vagabunda",


    // ofensas
    "idiota", "imbecil", "retardado", "retardada", "burro", "burra",
    "anta", "panaca", "otária", "otaria", "cretino", "cretina",
    "demente", "debilmental", "estúpido", "estupido", "estúpida", "estupida",
    "idiotice", "lerdo", "lerda", "mané", "mane", "trouxa",
    "paspalho", "paspalha", "mocorongo", "mocoronga", "jumento", "jumenta",
    "nojento", "nojenta", "escroto", "escrota", "canalha", "meliante",
    "vagal", "zicado", "zicada", "putao", "putona", "hitler","abusado", "molestado",
    "abusadao", "molestadao", "estrupado", "estrupadao", "gozadao", "gozador", "Veloso",
    "debiloide",


    //(vulgaridades/xingamentos comuns) ---
    "bacurinha", "baitola", "bichinha", "bichona", "bicha",
    "bilau", "bixa", "boceta", "boceta-molhada", "bolcinha",
    "bolsinha", "boiolao", "boquete", "boquetes", "boqueteira",
    "boqueteiro", "brecheca", "brocha", "brochado", "broche",
    "broxa", "broxeira", "bucefula", "buceta", "bucetao",
    "bucetas", "bucetinha", "bucetona", "bunda", "bundao",
    "bundona", "cabrao", "cachorra", "cachuleta", "cadela",
    "cafetao", "cafetina", "cagalhao", "caraio", "caralha",
    "caralhudo", "cassete", "cequelada", "chatico", "chavasca",
    "checheca", "chereca", "chibio", "chifrudo", "chimbica",
    "chupa-pau", "chupada", "chupador", "chupadora", "chupando",
    "chupeta", "chupetinha", "chupou", "comedor", "comedora",
    "comilona", "corna", "cornao", "corpao", "corpo-de-sereia",
    "crossdresser", "cuecao", "custozinha", "cuzinho", "dadeira",
    "delicia-de-corpo", "desgraca", "devassa", "devasso",
    "encoxada", "engolidor", "engolidora", "enrabadas",
    "enrustida", "enrustido", "escrotinho", "estuprador",
    "estupradora", "fornicada", "frescao", "fresco", "frescura",
    "fudendo", "fudido", "fudida", "furustreca",
    "garota-de-programa", "garoto-de-programa", "gostosao",
    "gostosona", "gostozudas", "gozada", "gozadas", "gozar",
    "gozo", "greludas", "gulosinha", "katchanga", "ladra",
    "ladrao", "lambeaba", "lambe-saco", "lambisgoia", "lamedor",
    "larapio", "lasciva", "lascivo", "lesbofetiche", "libidinosa",
    "libidinoso", "lixa-pica", "machona", "machorra",
    "masturbacao", "masturbar", "mede-rola", "megasex",
    "mela-pentelho", "meleca", "melequinha", "menage", "merdao",
    "meretriz", "metendo", "michê", "mijada", "mijao", "mijar",
    "mongoloide", "orgia", "bacanal", "papa-duro", "pausudas",
    "pechereca", "pedofila", "pedofilo", "peidao", "peido",
    "peidorreiro", "peitao", "peitona", "peituda", "peitudas",
    "pênis", "penis", "periquita", "perereca", "pepeca",
    "pica", "pinto", "piranhao", "piranhuda", "piriguete",
    "piriguetes", "piroca", "pirocao", "pirocudo", "pirulito",
    "pitbitoca", "pitchbicha", "pithbicha", "pitibicha",
    "pitrica", "pixota", "pornografica", "pornografico",
    "prencheca", "prexeca", "priquita", "priquito", "prostituta",
    "prostituto", "proxeneta", "punheta", "punhetao", "punheteira",
    "punheteiro", "pussy", "putaria", "putinha",
    "putinha-de-luxo", "quenga", "rabao", "rabuda", "rabudas",
    "rameira", "rapariga", "saca-rola", "safada", "safadinha",
    "safadinho", "safado", "sapatao", "sapatona", "sapatão",
    "sequelada", "sexboys", "sexgatas", "siliconada", "sirica",
    "siririca", "siririquenta", "sotravesti", "suruba", "surubas",
    "taioba", "tarada", "tarado", "tchaca", "tcheca", "tchonga",
    "tchuchuca", "tchutchuca", "tesao", "tesuda", "tesudas",
    "tesudo", "tetinha", "tezao", "tezuda", "tezudo", "tgatas",
    "tobinha", "tomba-macho", "topsexy", "transa", "transando",
    "traveca", "travecas", "traveco", "travecos", "trepada",
    "trepadas", "vaca", "vacilao", "vadjaina", "vagabundao",
    "vagabundona", "vaginismo", "vajoca", "veiaca", "veiaco",
    "viadao", "viadinho", "viadagem", "vibrador", "xabasca",
    "xana", "xaninha", "xatico", "xavasca", "xebreca", "xereca",
    "xexeca", "xexelento", "xibio", "xibiu", "xoroca", "xota",
    "xota-molhada", "xotinha", "xoxota", "xoxotinha", "xulipa",
    "xumbrega", "xupaxota", "xupeta", "xupetinha", "pau",
    "rola", "caralho", "punhetar", "cagar", "cagao", "cagão",
    "fudida", "fudeu", "fuder", "peidar", "masturbação",
    "masturbacao", "testículo", "testiculo", "clitóris", "clitoris",
    "pênis", "penis", "vagina", "vulva", "ânus", "anus", "aborto", 
    "escurinho", "xxxx", "bucetudo", "bucetuda", "caralhinhos",
    "makako", "makaka", "satanico", "molhadinho", "anal", "neguinho",
    "nigga", "nigger","xvideos", "pornhub", "cuceta", "cusseta", 
    "xhamster", "rule34", "hentai", "eroge", "erotico", "bussanha", 
    "pacotudo", "pacoteira", "sacudo", "sixseven", "pomperismo", 
];
export const abreviacoes = [
 "fds", "vsf", "pqp", "tnc", "vtnc", "tmnc",
    "f.d.s", "f.ds", "fd.s", "f_d_s", "fd_s", "f_ds",
    "f-d-s", "f,d,s", "v.s.f", "krl", "krlh", "crl", "crlh",
    "pq", "poha", "carai", "kct", "cct", "vsfd", "vsfdp",
];